### ISSUE TITLE
Hide answer for an unbiased input?

### ISSUE THREAD

**Issue by vyshnavsdeepak** [knadh/dont.build#5]
Currently, the answer shown is updated in a reactive manner with respect to the updates in input.

I guess hiding the answer while adjusting the range sliders will help avoid a cognitive bias.
I propose to include a toggle button to display or hide the answer. 

I have an implementation on my fork. Happy to send a PR if this will be useful.

https://github.com/vyshnavsdeepak/dont.build/tree/feature/hide-answer

**Comment by knadh** [comment]
Great suggestion! Please send a PR.

- Let's keep the answer hidden by default.
- Could you add this to the `button {}` style?
```css
font-size: 1.3rem;
border-width: 1px 3px 3px 1px;
border-style: solid;
border-radius: 3px;
```

**Comment by vyshnavsdeepak** [comment]
> Great suggestion! Please send a PR.
> 
> * Let's keep the answer hidden by default.
> * Could you add this to the `button {}` style?
> 
> ```css
> font-size: 1.3rem;
> border-width: 1px 3px 3px 1px;
> border-style: solid;
> border-radius: 3px;
> ```

Thanks @knadh . I have made the fixes.

**Comment by vyshnavsdeepak** [comment]
I should change the var to const as well

**Comment by knadh** [comment]
Merged. Thank you.
